// <auto-generated />
namespace bangazon_inc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removedMoreRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedMoreRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201705170131289_removedMoreRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
